// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/facility-dossier-review/Current.tsx": () => import("../components/mockups/facility-dossier-review/Current.tsx"),
  "./components/mockups/facility-dossier-review/Redesign.tsx": () => import("../components/mockups/facility-dossier-review/Redesign.tsx"),
  "./components/mockups/menu-list/Current.tsx": () => import("../components/mockups/menu-list/Current.tsx"),
  "./components/mockups/menu-list/Refined.tsx": () => import("../components/mockups/menu-list/Refined.tsx")
};
